name: exelbid_plugin
description: "Exelbid SDK for Flutter"
version: 1.1.4
repository: https://github.com/onnuridmc/Exelbid_Plugin

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.motivi.exelbid_plugin
        pluginClass: ExelbidPlugin
      ios:
        pluginClass: ExelbidPlugin
